Fix flask-simulator deployment.yaml - 2

diff --git a/platform-apps/flask-simulator/templates/simulator-deployment.yaml b/platform-apps/flask-simulator/templates/simulator-deployment.yaml
--- a/platform-apps/flask-simulator/templates/simulator-deployment.yaml
+++ b/platform-apps/flask-simulator/templates/simulator-deployment.yaml
@@ -27,8 +27,7 @@ spec:
               while true; do
               {{- range .Values.simulator.endpoints }}
                 echo "Calling endpoint: {{ .path }}"
-                curl --max-time {{ $.Values.simulator.curl_timeout_seconds }}
-                  -s http://flask-app:5000{{ .path }} || echo "Failed: {{ .path }}";
+                curl -s --max-time {{ $.Values.simulator.curl_timeout_seconds }} http://flask-app:5000{{ .path }} || echo "Failed: {{ .path }}";
               {{- end }}
                 sleep $SLEEP_INTERVAL;
               done
